#
# Welcome!
#
# This file is the master Gemfile for QSA's ArchivesSpace installation, and
# includes the gem dependencies of all of the plugins in one file.
#
# If you need to add/change/remove a gem dependency, you can do so at the bottom
# of this file.
#
# Previously each plugin had its own Gemfile, but this caused headaches.
# Sometimes a plugin would have a dependency (or a transitive dependency) on a
# gem that was already present in the core ArchivesSpace build, and we would end
# up with two different versions of the same gem installed.  Depending on how
# bundler felt on the day, this would sometimes prevent the system from starting
# up.
#
# So now we add all dependencies here.  This helps because this Gemfile is
# loaded as a part of building the ArchivesSpace distribution, so Bundler can
# determine a set of gem dependencies that satisfy ArchivesSpace as well as the
# needs of the QSA plugins.  It also means any incompatibilities can be flagged
# at build time, rather than only finding out when the system fails to start.
#

$stderr.puts "LOADING QSA GEMS"

ASpaceGems.setup if defined? ASpaceGems

# If you change these, you may want to rm -rf ./local_gems/ and rerun
# bootstrap.sh to pull down your updated versions.
local_gems = [
  {
    gem: "xlsx_streaming_reader",
    url: "git@gitlab.gaiaresources.com.au:qsa/xlsx_streaming_reader.git",
    ref: ENV.fetch("GIT_REF", "origin/develop"),
  },
  {
    gem: "qsa_shared",
    url: "git@gitlab.gaiaresources.com.au:qsa/qsa_shared.git",
    ref: ENV.fetch("GIT_REF", "origin/develop"),
  },
  {
    gem: "map_validator",
    url: "git@gitlab.gaiaresources.com.au:qsa/map_validator.git",
    ref: ENV.fetch("GIT_REF", "origin/develop"),
  },
]


local_gems_path = File.join(File.dirname(__FILE__), "local_gems")

FileUtils.mkdir_p(local_gems_path)

local_gems.each do |gem|
  checkout_dir = File.join(local_gems_path, gem.fetch(:gem))

  if $0 == "gems/bin/bundle"
    # We're running a bootstrap.  Make sure we have the latest version of our
    # dependency.  If it's a symlink, we assume you know what you're doing.
    if File.exist?(File.join(checkout_dir, '.git')) && !File.symlink?(checkout_dir)
      $stderr.puts("Resetting '%s' to %s" % [checkout_dir, gem[:ref]])
      system("git", "-C", checkout_dir, "fetch", "origin")
      unless system("git", "-C", checkout_dir, "reset", "--hard", gem.fetch(:ref))
        raise "Failure while selecting version of dependency: #{gem.inspect}"
      end
    end
  end

  # If the gem hasn't been checked out to local_gems/, grab a copy now.
  unless Dir.exist?(checkout_dir)
    system("git", "clone", gem.fetch(:url), checkout_dir)
    unless system("git", "-C", checkout_dir, "reset", "--hard", gem.fetch(:ref))
      raise "Failure while selecting version of dependency: #{gem.inspect}"
    end
  end

  # Add to load path
  $LOAD_PATH << File.join(checkout_dir, 'lib')
end

# Require dependencies
local_gems.each do |gem|
  require gem.fetch(:gem)
end

source 'https://rubygems.org'

gem "aws-sdk-s3", "1.138.0"
gem "aws-sdk-sqs", "1.67.0"
gem "mime-types", "3.5.2"
gem "mime-types-data", "3.2024.0507"

gem "html2text", "0.2.1"
