topics:
  # Resources
  resource: series
  resource_basic_information: series#creating-a-series
  resource_dates: series#creating-a-series
  resource_subjects: subjects
  resource_notes: series#notes
  resource_external_documents: series#resources
  series_system_resource_to_series: series#series-to-series-relationships
  series_system_resource_to_agent: series#relationships
  series_system_resource_to_mandate: series#relationships
  series_system_resource_to_function: series#relationships
  resource_external_ids: series
  resource_rap_attached: rap#attaching-raps-to-series
  resource_deaccessions: items#deaccessioning-items
  resource_rap_summary: rap#view-rap-history-and-summary
  # Functionszzz
  function: functions-and-mandates
  function_basic_information: functions-and-mandates#creating-functions
  function_date: functions-and-mandates
  function_non_preferred_names: functions-and-mandates
  series_system_function_to_function: entity-relationships#function-function
  series_system_function_to_agent: entity-relationships#agent-function
  series_system_function_to_mandate: entity-relationships#mandate-function
  # Mandates
  mandate: functions-and-mandates
  mandate_basic_information: functions-and-mandates#creating-mandates
  mandate_date: functions-and-mandates#creating-mandates
  series_system_mandate_to_mandate: entity-relationships#mandate-mandate
  series_system_mandate_to_function: entity-relationships#mandate-function
  series_system_mandate_to_agent: entity-relationships#agency-mandate
  mandate_external_ids: functions-and-mandates
  # Archival Objects
  archival_object: items
  archival_object_basic_information: items#creating-items
  archival_object_dates: items#creating-items
  archival_object_subjects: subjects
  archival_object_notes: items#notes
  archival_object_external_documents: series#resources
  archival_object_rap_applied: items#attaching-raps-to-items
  archival_object_rights_statements: items
  archival_object_external_ids: items#persistent-identifiers
  # Subjects
  subject: subjects
  subject_basic_information: subjects
  subject_terms: subjects
  subject_external_documents: subjects
  # Agent Persons
  agent_person: system-functions#users
  agent_person_basic_information: system-functions#users
  agent_person_dates_of_existence: system-functions#users
  agent_person_use_dates: system-functions#users
  agent_person_names: system-functions#users
  agent_person_contact_details: system-functions#users
  agent_person_notes: system-functions#users
  agent_name_use_dates: system-functions#users
  # Agent Corporate Entity
  agent_corporate_entity: agencies
  agent_corporate_entity_basic_information: agents#creating-agencies
  agent_corporate_entity_dates_of_existence: agencies#agency-dates
  agent_corporate_entity_names: agencies#agency-accs
  agent_corporate_entity_notes: agencies#notes
  agent_corporate_entity_external_documents: agencies#external-resources
  series_system_agent_corporate_entity_to_agent: entity-relationships#agency-agency
  series_system_agent_corporate_entity_to_mandate: entity-relationships#agent-agency-mandate
  series_system_agent_corporate_entity_to_function: entity-relationships#agent-agent-function
  # Physical Representation
  physical_representation: representations
  physical_representation_basic_information: representations#add-physical-representation-to-item
  physical_representation_date: representations
  physical_representation_rap_applied: rap
  physical_representation_movements: locattions-containers-movements
  # Digital Representation
  digital_representation: representations
  digital_representation_basic_information: representations#add-digital-representation-to-item
  digital_representation_date: representations
  digital_representation_rap_applied: rap
  digital_representation_file_issues: representations#file-issue
  digital_representation_deaccessions: representations#deaccession-reps-agency
  digital_representation_external_references: representations
  # Location
  location: locations-containers-movements
  location_functions: locations-containers-movements
  location_external_ids: locations-containers-movements
  # Event
  event: /
  event_basic_information: /
  event_date: /
  event_linked_agents: /
  event_linked_records: /
  # Classification
  classification: /
  # Classification Term
  classification_term: /
  # Import
  import: import
  # Search
  search: search
  # Manage Groups
  repository_groups: system-functions#groups
  # Managing User Access
  repository_users: system-functions#users
  # Repositories
  repository: /
  # Manage Users
  user: system-functions#users
  # Controlled Value Lists
  enumeration: /
  # Reading room requests
  reading_room_requests: staff-functions
  reading_room_requests_basic_information: staff-functions
  reading_room_requests_requested_item: staff-functions
  # Conservation Requests
  conservation_request: conservation-request
  conservation_request_basic_information: conservation-request#basic-information
  conservation_request_representations_requested: conservation-request#representations-requested
  # Batches
  batch: common-functions
  batch_basic_information: common-functions
  # Jobs
  job: /
  # Top Containers
  top_container: locations-containers-movements#creating-top-container
  top_container_movements: locations-containers-movements#movement-of-top-containers
